- name: Query Endpoints for target_clusters
  gather_facts: false
  hosts: localhost
  roles:
    - role: posthook-omc-haproxy-discover

- name: Configure HAProxy
  become: true
  gather_facts: false
  hosts: omc-ltm.lab.uc2.io
  roles:
    - role: posthook-omc-haproxy
