- name: Query Endpoints for target_clusters
  gather_facts: no
  hosts: localhost
  roles:
    - name: posthook-omc-haproxy-discover

- name: Configure HAProxy
  become: yes
  gather_facts: no
  hosts: omc-ltm.lab.uc2.io
  roles:
    - name: posthook-omc-haproxy
